#!/bin/bash
# ~/.bashrc.d/bash_prompt

# shamelessly stolen from https://github.com/devcontainers/features/blob/main/src/common-utils/scripts/bash_theme_snippet.sh
__bash_prompt() {
  unset -f __bash_prompt

  local userpart='`export XIT=$? \
    && echo -n "\[\033[0;32m\]\u " && [ "$XIT" -ne "0" ] && echo -n "\[\033[1;31m\]➜" || echo -n "\[\033[0m\]➜"`'
  local gitbranch='`\
    export BRANCH="$(git --no-optional-locks symbolic-ref --short HEAD 2>/dev/null || git --no-optional-locks rev-parse --short HEAD 2>/dev/null)"; \
    if [ "${BRANCH:-}" != "" ]; then \
      echo -n "\[\033[0;36m\](\[\033[1;31m\]${BRANCH:-}" \
      && if git --no-optional-locks ls-files --error-unmatch -m --directory --no-empty-directory -o --exclude-standard ":/*" > /dev/null 2>&1; then \
        echo -n " \[\033[1;33m\]✗"; \
      fi \
      && echo -n "\[\033[0;36m\]) "; \
    fi`'
  local lightblue='\[\033[1;34m\]'
  local removecolor='\[\033[0m\]'

  PS1="${userpart} ${lightblue}\w ${gitbranch}${removecolor}\$ "
}
__bash_prompt
export PROMPT_DIRTRIM=4
