#!/bin/bash
# ~/.bashrc.d/configure_ssh-agent

__configure_ssh-agent() {
  unset -f __configure_ssh-agent

  unset SSH_AGENT_PID
  if [ "${gnupg_SSH_AUTH_SOCK_by:-0}" -ne $$ ]; then
    export SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"
  fi
}
__configure_ssh-agent
